name: .NET

on:
  push:
    branches: [ "dev" ]
  release:
    types: [published]
    tags:
      - '*.*.*'
  workflow_dispatch:  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build
    - name: Get package info
      id: package-info
      run: |
        NAME=$(jq -r '.name' manifest.json)
        VERSION_NUMBER=$(jq -r '.version_number' manifest.json)
        DESCRIPTION=$(jq -r '.description' manifest.json)
        WEBSITE_URL=$(jq -r '.website_url' manifest.json)
        DEPENDENCIES=$(jq -r '.dependencies | join(" ")' manifest.json)
        echo "::set-output name=name::$NAME"
        echo "::set-output name=version_number::$VERSION_NUMBER"
        echo "::set-output name=description::$DESCRIPTION"
        echo "::set-output name=website_url::$WEBSITE_URL"
        echo "::set-output name=dependencies::$DEPENDENCIES"
    - name: Display package info
      run: |
        echo "Name: ${{ steps.package-info.outputs.name }}"
        echo "Version Number: ${{ steps.package-info.outputs.version_number }}"
        echo "Description: ${{ steps.package-info.outputs.description }}"
        echo "Website URL: ${{ steps.package-info.outputs.website_url }}"
        echo "Dependencies: ${{ steps.package-info.outputs.dependencies }}"
    - name: Zip files
      run: |
        zip -r "${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version_number }}.zip" "manifest.json" "icon.png" "README.md" "CHANGELOG.md" "BetterLadders/bin/Debug/netstandard2.1/BetterLadders.dll"
    - name: Upload to Thunderstore
      uses: GreenTF/upload-thunderstore-package@v4.3
      with:
        namespace: e3s1
        description: ${{ steps.package-info.outputs.description }}
        token: ${{ secrets.TS_API_KEY }}
        name: ${{ steps.package-info.outputs.name }}
        version: ${{ steps.package-info.outputs.version_number }}
        community: lethal-company
        repo: thunderstore.io
        website: ${{ steps.package-info.outputs.website_url }}
        deps: ${{ steps.package-info.outputs.dependencies }}
        file: "${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version_number }}.zip"
        categories: |
          bepinex
          mods
          clientside
          serverside
          misc
